### ISSUE TITLE
setup error

### ISSUE THREAD

**Issue by PranceLi** [xoureldeen/Vectras-VM-Android#104]
![Screenshot_2024-07-09-16-22-11-788_com vectras vm](https://github.com/xoureldeen/Vectras-VM-Android/assets/5248978/195704bf-9d4b-4d56-8c07-93266b6b885f)

I got gzip:invalid magic error when setup vectras

**Comment by xoureldeen** [comment]
THE FUCKING APP SUSPENDED

**Comment by PranceLi** [comment]
> THE FUCKING APP SUSPENDED

why? Is there any problem? I think your work is awesome ^_^

**Comment by xoureldeen** [comment]
> > THE FUCKING APP SUSPENDED
> 
> why? Is there any problem? I think your work is awesome ^_^

Sorry but we working on rebase this project

**Comment by PranceLi** [comment]
> > > THE FUCKING APP SUSPENDED
> > 
> > 
> > why? Is there any problem? I think your work is awesome ^_^
> 
> Sorry but we working on rebase this project

really looking forward to your coming back
