### ISSUE TITLE
Are there any plans to support languages other than English?

### ISSUE THREAD

**Issue by adk23333** [xoureldeen/Vectras-VM-Android#129]
As described in the title...

**Comment by xoureldeen** [comment]
You can contribute by creating a values-LANG/strings.xml file, where LANG is the language code you wish to support (e.g., values-es for Spanish). Add translations for all the strings in the original strings.xml file. Feel free to submit a pull request with your changes.

**Comment by adk23333** [comment]
> You can contribute by creating a values-LANG/strings.xml file, where LANG is the language code you wish to support (e.g., values-es for Spanish). Add translations for all the strings in the original strings.xml file. Feel free to submit a pull request with your changes. 

Thank you for your detailed reply.
