### ISSUE TITLE
ROMs page on website 404 NOT FOUND

### ISSUE THREAD

**Issue by KeiranGamingTV** [xoureldeen/Vectras-VM-Android#130]
See attached video:
[Screen recording 2024-11-04 12.24.27 PM.webm](https://github.com/user-attachments/assets/7113237e-dff9-4d04-ab2c-fe5f96de5539)

**Comment by xoureldeen** [comment]
> See attached video: [Screen recording 2024-11-04 12.24.27 PM.webm](https://github.com/user-attachments/assets/7113237e-dff9-4d04-ab2c-fe5f96de5539)

don't waste ur time and check the app, u will find store button in the drawer.........

**Comment by KeiranGamingTV** [comment]
what do you mean by "u will find store button in the drawer?"

also, do you mean "don't waste my time. go check the app." or "don't waste my time checking the app?"

**Comment by xoureldeen** [comment]
> what do you mean by "u will find store button in the drawer?"
> 
> also, do you mean "don't waste my time. go check the app." or "don't waste my time checking the app?"

ur time, install the app and u will discover it

**Comment by rahim-gh** [comment]
what about when: no drawer. also error with exit code 6 on auto setup
