### ISSUE TITLE
Can't downloads roms from https://vectras.vercel.app/roms.html  404: NOT_FOUND

### ISSUE THREAD

**Issue by N-harzallah** [xoureldeen/Vectras-VM-Android#139]
Hello,

Can't downloads roms from https://vectras.vercel.app/roms.html 

404: NOT_FOUND Code: NOT_FOUND ID: cdg1::w2fgn-1731413710481-ca46e5e7760d

**Comment by xoureldeen** [comment]
![Screenshot_2024-11-12-14-25-40-768_com vectras vm-edit](https://github.com/user-attachments/assets/dee4e684-b26f-4637-a1fd-ffbbcbaa2cf6)
