### ISSUE TITLE
Anyone test on redmagic?

### ISSUE THREAD

**Issue by InfamousKnight** [xoureldeen/Vectras-VM-Android#141]
I was thinking about buying a red magic nova for this but am afraid it may not make any difference from samsung galaxy s23 fe.

If someone has any red magic device(excluding ree magic titan 16), could you test linux mint 12(the one from the rom store)?

**Comment by xoureldeen** [comment]
Red Magic is excellent but you have to keep in mind that this is a virtual machine with no acceleration kvm It is currently not supported. I advise you to use PRoot.
