### ISSUE TITLE
Virtualization

### ISSUE THREAD

**Issue by ItsWinterBush** [xoureldeen/Vectras-VM-Android#144]
add 3d acceleration and hvf used by utm and
install full qemu system

**Comment by xoureldeen** [comment]
> add 3d acceleration and hvf used by utm and install full qemu system

thanks for suggesting, we already started to bring back 3d acceleration to be added in 2.9.5

**Comment by ItsWinterBush** [comment]
thx

**Comment by ItsWinterBush** [comment]
thanks for support
