### ISSUE TITLE
Xiaomi Redmi A3 (Android 14)

### ISSUE THREAD

**Issue by EriCashier** [xoureldeen/Vectras-VM-Android#161]
Redmi Android 14 System MIUI (ITS NOT HYPER OS)
its supported?
Processor: Octa-Core Mediatek Helio G36

**Comment by xoureldeen** [comment]
read the readme.md and don't annoy us please.

**Comment by EriCashier** [comment]
Please Don't dox just because is showing my IP address please

**Comment by xoureldeen** [comment]
@EriCashier you mean what?


![394477162-5f9fbca9-2343-4a5d-a970-0b17e1cb566e.png](https://github.com/user-attachments/assets/9ba522cf-9ad4-4b8c-8bcb-d8cc18f9386b)

![Screenshot_2024-12-11-00-24-42-861_com.google.android.gm.jpg](https://github.com/user-attachments/assets/70035317-7f08-4c90-a22b-67c268af7f12)

**Comment by EriCashier** [comment]
Look on the IP Address at my phone's settings 
I was showing you my build number.

**Comment by xoureldeen** [comment]
> Look on the IP Address at my phone's settings 
> I was showing you my build number.

ohh ok, but i like this ip address
