### ISSUE TITLE
Add ARM64 Image for GXDE-OS

### ISSUE THREAD

**Issue by SunnyPai0413** [xoureldeen/Vectras-VM-Android#169]
Greetings Vectras Team,

I've added the ARM64 image to our file server. Since your project runs on the Android AArch64 platform, we have only built the ARM64 disk image. Please note that we do not currently support i386 and PPC architectures. If you require support for the AMD64 platform, feel free to contact me. The disk image has been thoroughly tested on the QEMU virtualization platform.

The UEFI drive used to boot our system was extracted from your VM app, so no additional files are required. Keeping everything as default should suffice for running the system.

**Download URL**:  
[qcow2-image](https://directshare.spark-app.store/gxde-os.qcow2)  
*This is the main ARM64 image for the Android AArch64 platform.*

**TGZ File for Faster Transfer**:  
[qcow2-tgz](https://directshare.spark-app.store/gxde-os.qcow2.tar.gz)  
*Use this compressed file to accelerate download speeds.*

**Logo URL**:  
[gxde-logo](https://www.gxde.org/logo.png)  
*This is the logo for the project.*

Please review the image and let me know if there are any issues or further improvements needed.

With appreciation,

SunnyPai  
DevOps Engineer  
GXDE OS Team

**Comment by xoureldeen** [comment]
ok, have u tested it on vectras?, because arm64 is experimental

**Comment by SunnyPai0413** [comment]
Sorry but not yet tested.
My only android device Redmi Note5 failed to initialize the app. 
The error shows that it failed to download QEMU because curl has no URL specified.
~~My boyfriend recommended this app to me, but he is not a part of GXDE Team, and on his way now back to school for final examination just an hour before qemu image was built.~~
So may you test it on your platform? Thanks a lot...

Additionally, the system has very colorful effects, so make sure you have enough memory and high performance before choosing the effects mode.

**Comment by xoureldeen** [comment]
can i ask which kernel is ur os based on, and why it has that's huge size, can i get more information, Because I'm curious, thank you

**Comment by xoureldeen** [comment]
> Sorry but not yet tested.
> My only android device Redmi Note5 failed to initialize the app. 
> The error shows that it failed to download QEMU because curl has no URL specified.
> ~~My boyfriend recommended this app to me, but he is not a part of GXDE Team, and on his way now back to school for final examination just an hour before qemu image was built.~~
> So may you test it on your platform? Thanks a lot...
> 
> Additionally, the system has very colorful effects, so make sure you have enough memory and high performance before choosing the effects mode.

great, i will test it tomorrow, thanks

**Comment by SunnyPai0413** [comment]
> can i ask which kernel is ur os based on, and why it has that's huge size, can i get more information, Because I'm curious, thank you

GXDE (Gorgeous eXtended Deepin Environment) is based on Debian12, linux kernel, and added DDE (Deepin Desktop Environment) as default, with a lot of Gorgeous visual effects, so it is a huge size.

**Comment by xoureldeen** [comment]
> > Sorry but not yet tested.
> > My only android device Redmi Note5 failed to initialize the app.
> > The error shows that it failed to download QEMU because curl has no URL specified.
> > ~My boyfriend recommended this app to me, but he is not a part of GXDE Team, and on his way now back to school for final examination just an hour before qemu image was built.~
> > So may you test it on your platform? Thanks a lot...
> > Additionally, the system has very colorful effects, so make sure you have enough memory and high performance before choosing the effects mode.
> 
> great, i will test it tomorrow, thanks

this image has too weight size so its uncomfortable for the store currently, so i will install and test x86_64 which is may have smaller size, thank you

**Comment by AnBui2004** [comment]
> Greetings Vectras Team,
> 
> I've added the ARM64 image to our file server. Since your project runs on the Android AArch64 platform, we have only built the ARM64 disk image. Please note that we do not currently support i386 and PPC architectures. If you require support for the AMD64 platform, feel free to contact me. The disk image has been thoroughly tested on the QEMU virtualization platform.
> 
> The UEFI drive used to boot our system was extracted from your VM app, so no additional files are required. Keeping everything as default should suffice for running the system.
> 
> **Download URL**: [qcow2-image](https://directshare.spark-app.store/gxde-os.qcow2) _This is the main ARM64 image for the Android AArch64 platform._
> 
> **TGZ File for Faster Transfer**: [qcow2-tgz](https://directshare.spark-app.store/gxde-os.qcow2.tar.gz) _Use this compressed file to accelerate download speeds._
> 
> **Logo URL**: [gxde-logo](https://www.gxde.org/logo.png) _This is the logo for the project._
> 
> Please review the image and let me know if there are any issues or further improvements needed.
> 
> With appreciation,
> 
> SunnyPai DevOps Engineer GXDE OS Team

What's password?

**Comment by SunnyPai0413** [comment]
> > Greetings Vectras Team,
> > I've added the ARM64 image to our file server. Since your project runs on the Android AArch64 platform, we have only built the ARM64 disk image. Please note that we do not currently support i386 and PPC architectures. If you require support for the AMD64 platform, feel free to contact me. The disk image has been thoroughly tested on the QEMU virtualization platform.
> > The UEFI drive used to boot our system was extracted from your VM app, so no additional files are required. Keeping everything as default should suffice for running the system.
> > **Download URL**: [qcow2-image](https://directshare.spark-app.store/gxde-os.qcow2) _This is the main ARM64 image for the Android AArch64 platform._
> > **TGZ File for Faster Transfer**: [qcow2-tgz](https://directshare.spark-app.store/gxde-os.qcow2.tar.gz) _Use this compressed file to accelerate download speeds._
> > **Logo URL**: [gxde-logo](https://www.gxde.org/logo.png) _This is the logo for the project._
> > Please review the image and let me know if there are any issues or further improvements needed.
> > With appreciation,
> > SunnyPai DevOps Engineer GXDE OS Team
> 
> What's password?

Sorry, forgot to tell you
The password is `123456` . And the default user is sudoers.

**Comment by AnBui2004** [comment]
![image](https://github.com/user-attachments/assets/5d53eb22-4a01-4741-8c21-a0a0b4dff921)
![image](https://github.com/user-attachments/assets/f561789b-4d0a-4572-bbbc-4194cb291263)
Now it is available on Rom store.

**Comment by xoureldeen** [comment]
Done! ✅
