### ISSUE TITLE
Vectras Vm setting up issue 

### ISSUE THREAD

**Issue by Bilawal70** [xoureldeen/Vectras-VM-Android#173]
I installed the emulator and tapped auto setup and this is the fail I got.

proot error: ptrace(TRACEME): Operation not permitted
proot error: ptrace(TRACEME): Operation not permitted
proot error: execve("/bin/sh"): Operation not permitted
proot info: It seems your kernel contains this bug: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1202161
To workaround it, set the env. variable PROOT_NO_SECCOMP to 1.
fatal error: see `proot --help`.
proot error: can't chmod '/data/data/com.vectras.vm/files/usr/tmp/proot-32387-zlwcmf': No such file or directory
proot error: execve("/bin/sh"): Operation not permitted
proot info: It seems your kernel contains this bug: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1202161
To workaround it, set the env. variable PROOT_NO_SECCOMP to 1.
fatal error: see `proot --help`.
proot error: can't chmod '/data/data/com.vectras.vm/files/usr/tmp/proot-32388-nH5ZbW': No such file or directory
Error: Command failed with exit code: 1
Error: Command failed with exit code: 1
![Screenshot_20241221-181251](https://github.com/user-attachments/assets/6f2a0d6b-e244-4259-bfd0-1b14805a945d)

**Comment by xoureldeen** [comment]
what device u r using?

**Comment by Bilawal70** [comment]
Arrows F-02k

**Comment by xoureldeen** [comment]
it's not supported.

**Comment by Bilawal70** [comment]
Ok
