### ISSUE TITLE
Suggest to improve performance

### ISSUE THREAD

**Issue by ahmed-alnassif** [xoureldeen/Vectras-VM-Android#183]
I've noticed that Vectras VM uses QEMU through a proot Alpine Linux environment. While this setup provides isolation, it introduces additional overhead that affects performance.
Running QEMU directly within the app, without the proot layer, would likely improve performance and simplify the app's architecture, If Alpine's tools or configurations are necessary, these could be integrated natively within the app instead.

**Comment by xoureldeen** [comment]
> I've noticed that Vectras VM uses QEMU through a proot Alpine Linux environment. While this setup provides isolation, it introduces additional overhead that affects performance. Running QEMU directly within the app, without the proot layer, would likely improve performance and simplify the app's architecture, If Alpine's tools or configurations are necessary, these could be integrated natively within the app instead.

vectras is different due 3dfx and more features can't be ported to android due kernel limitations which will make qemu much slower, the app was native till 2.7 and moved to out patched proot, you can compare performance between vectras and other qemu emulators on android.

in termux u can't use cores more than 1 core,
in limbo you have old version due kernel limitations, and there is alot things are not supported like qxl and 3dfx and spice, which all of them exist in vectras with better performance and stability, thank you.
