### ISSUE TITLE
New vectras build crashing when trying to add bootstrap

### ISSUE THREAD

**Issue by GamerLoganDean** [xoureldeen/Vectras-VM-Android#49]
Here is the error it told me:

proot error: execve("/bin/sh"): Function not implemented
proot info: possible causes:
  * the program is a script but its interpreter (eg. /bin/sh) was not found;
  * the program is an ELF but its interpreter (eg. ld-linux.so) was not found;
  * the program is a foreign binary but qemu was not specified;
  * qemu does not work correctly (if specified);
  * the loader was not found or doesn't work.
fatal error: see `libproot.so --help`.
Error: Command failed with exit code: 1
proot error: execve("/bin/sh"): Function not implemented
proot info: possible causes:
  * the program is a script but its interpreter (eg. /bin/sh) was not found;
  * the program is an ELF but its interpreter (eg. ld-linux.so) was not found;
  * the program is a foreign binary but qemu was not specified;
  * qemu does not work correctly (if specified);
  * the loader was not found or doesn't work.
fatal error: see `libproot.so --help`.
proot warning: ptrace(PEEKDATA): I/O error
proot error: can't chmod '/data/user/0/com.vectras.vm/files/tmp/proot-15365-8WhUCG': Function not implemented
proot error: can't chdir to '': Function not implemented
Error: Command failed with exit code: 1
proot error: execve("/bin/sh"): Function not implemented
proot info: possible causes:
  * the program is a script but its interpreter (eg. /bin/sh) was not found;
  * the program is an ELF but its interpreter (eg. ld-linux.so) was not found;
  * the program is a foreign binary but qemu was not specified;
  * qemu does not work correctly (if specified);
  * the loader was not found or doesn't work.
fatal error: see `libproot.so --help`.
Error: Command failed with exit code: 1
proot error: execve("/bin/sh"): Function not implemented
proot info: possible causes:
  * the program is a script but its interpreter (eg. /bin/sh) was not found;
  * the program is an ELF but its interpreter (eg. ld-linux.so) was not found;
  * the program is a foreign binary but qemu was not specified;
  * qemu does not work correctly (if specified);
  * the loader was not found or doesn't work.
fatal error: see `libproot.so --help`.
proot warning: ptrace(PEEKDATA): I/O error
proot error: can't chmod '/data/user/0/com.vectras.vm/files/tmp/proot-15533-fTYjFh': Function not implemented
proot error: can't chdir to '': Function not implemented
Error: Command failed with exit code: 1

**Comment by epicstudios856** [comment]
@GamerLoganDean Ur android version still not supported

**Comment by GamerLoganDean** [comment]
> @GamerLoganDean Ur android version still not supported

Damn that sucks. It's prolly the latest cause it's the S24 Ultra

**Comment by EdyDeveloper** [comment]
Same issue on my S24 Ultra. Android 14, OneUI 6.1
![Screenshot_20240427_104642_Vectras VM.png](https://github.com/epicstudios856/Vectras-VM-Android/assets/63300247/bb45a662-2b29-4411-b8d1-97d225e0ca50)

**Comment by GamerLoganDean** [comment]
> Same issue on my S24 Ultra. Android 14, OneUI 6.1 ![Screenshot_20240427_104642_Vectras VM.png](https://private-user-images.githubusercontent.com/63300247/326163950-bb45a662-2b29-4411-b8d1-97d225e0ca50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMTE2MjUsIm5iZiI6MTcxNDIxMTMyNSwicGF0aCI6Ii82MzMwMDI0Ny8zMjYxNjM5NTAtYmI0NWE2NjItMmIyOS00NDExLWI4ZDEtOTdkMjI1ZTBjYTUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDA5NDg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0YmQyNWY3NmZhMTE3YzI5NTRiOTM4ZDk0MWNmZGJjZmZkYmFhYjUwOTZjNTAwMWU4OTI3YmVmYjBlMDUyNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aSJQW6ZMLBxqUaDAa05dy8mgwy9gghkfPS9EJF46hnk)

Yeah it obviously isn't optimised for the latest version of Android yet if it give you the same error on the same phone.

**Comment by epicstudios856** [comment]
Prootnuses multi arch 23bit and 64bit so s24 ultra cpu dosent support 32bit

**Comment by EdyDeveloper** [comment]
> Prootnuses multi arch 23bit and 64bit so s24 ultra cpu dosent support 32bit

So there's no way to ever make it work on the S24? What about the European Exynos 2400 variants (S24/S24+)?

**Comment by epicstudios856** [comment]
@EdyDeveloper I will work on it when im free

**Comment by EdyDeveloper** [comment]
> @EdyDeveloper I will work on it when im free

Thanks a lot! It's no rush tho.

**Comment by tpkarras** [comment]
hi. having similar problems with A14 Xiaomi 14 Ultra. 

Log is below.

`proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/bin/sh' not found (root = /data/user/0/com.vectras.vm/files/distro, cwd = /, $PATH=(null))
fatal error: see libproot.so --help.
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/bin/sh' not found (root = /data/user/0/com.vectras.vm/files/distro, cwd = /, $PATH=(null))
fatal error: see libproot.so --help.
Error: Command failed with exit code: 1
Error: Command failed with exit code: 1`

**Comment by epicstudios856** [comment]
@tpkarras USE THE FUCKIN LATEST APK ._.

**Comment by GamerLoganDean** [comment]
> @tpkarras USE THE FUCKIN LATEST APK ._.

Still doesn't work for me on my s24 ultra

**Comment by phoenixbyrd** [comment]
Same issue on my s24u with latest apk

**Comment by GamerLoganDean** [comment]
> Same issue on my s24u with latest apk
I doubt s24 will get it since android 15 is coming soon and android 14 still doesn't have it. I can't believe people are replying cockily too even though months later it still doesn't work.

**Comment by xoureldeen** [comment]
fixed
