### ISSUE TITLE
Vectras-VM at OpenAPK

### ISSUE THREAD

**Issue by gdimoff** [xoureldeen/Vectras-VM-Android#73]
Hey,

I'm running a open source repo for Android apps at https://www.openapk.net and I would like to have JellyBook listed in the repo. Please review the listing at https://www.openapk.net/vectras-vm/com.vectras.vm/

It is hooked to your GitHub repo so all the updates are automatically pushed to OpenAPK. Let me know if its ok !

If you are interested you can link to it and use our download banners ( https://www.openapk.net/images/openapk-badge.png )

![openapk-badge](https://github.com/epicstudios856/Vectras-VM-Android/assets/274414/4a61c310-d423-444d-b2fb-294fddeeeb58)

**Comment by xoureldeen** [comment]
hello @gdimoff can u update the username and releases?

**Comment by gdimoff** [comment]
updated !

**Comment by xoureldeen** [comment]
thanks!
