### ISSUE TITLE
try again later) Error: Command failed with exit code: 6

### ISSUE THREAD

**Issue by Stiven2016** [xoureldeen/Vectras-VM-Android#75]
try again later)
Error: Command failed with exit code: 6

**Comment by ahmedbarakat2007** [comment]
Reset app data and try again

this issue is caused bcuz your internet connection is slow

**Comment by hamedbilea11** [comment]
![Screenshot_٢٠٢٤٠٥٢٦_٠٣٢٠٠٣_Vectras VM](https://github.com/epicstudios856/Vectras-VM-Android/assets/92235654/ed02efa8-8fe0-48b4-b1ff-6ff637300229)

**Comment by hamedbilea11** [comment]
I have this problem
![Screenshot_٢٠٢٤٠٥٢٦_٠٣٢٠٠٣_Vectras VM](https://github.com/epicstudios856/Vectras-VM-Android/assets/92235654/975bb380-e520-4e97-9143-e304332ab430)

**Comment by xoureldeen** [comment]
fixed
