### ISSUE TITLE
General issues with the app

### ISSUE THREAD

**Issue by meetioss** [xoureldeen/Vectras-VM-Android#85]
The app has a number of issues which make it unuseable 
I am using an asus rogphone 7, android 13 

First off, the app imports files to its own folder, making duplicates. This is an intended feature, but I find it annoying since it eats up space
Second, the app has an issue saving settings, I've had roms that I deleted randomly show up again
Third, rarely do I get to start up roms since the app regularly throws up errors about being unable to get the "write" lock. Cdroms don't seem to work at all, I couldn't get a single one to boot 
Fourth, the app often crashes when in the vm, sometimes for no reason, sometimes it crashes when I try to switch to the QEMU terminal
Fifth, starting up a VM seemingly gets cancelled when I turn the phone from portrait to landscape and vice versa. Same things happens when I launch up the "tiny vterm" terminal 
Also, there's no option to reset the VM, meaning that if I want to restart a crashed OS (for example), I have to close and reopen it 
Also also, the app doesn't recognize files in capitalized .iso format ('.ISO" instead of ".iso")
Also also also, the app doesn't handle folders with spaces in their names very well, causing issues with the qemu prompt 

There's also no audio output, but I presume this is just unimplemented and probably will be added in the future 

Also, the app doesn't support ".png" images, which makes things a bit inconvenient 

If I could request some features: Qemu has the ability to create an ISO from a selected folder. Some OSes are a bit buggy with shared folders so I figured this could be a helpful alternative

**Comment by xoureldeen** [comment]
:)
