### ISSUE TITLE
Doesn't output sound to SPICE.

### ISSUE THREAD

**Issue by Wirdi51** [xoureldeen/Vectras-VM-Android#91]
Hello everyone, this is my first time writing in Github, I use **Vectras v2.9.1**, to conveniently use QXL GPU, for **Windows 7 Ultimate x64**, installed on this system **guest-client-tools** and I use [aSPICE](https://play.google.com/store/apps/details?id=com.iiordanov.aSPICE) (SPICE Client for Android).

The problem is that the sound is not output SPICE client, I configured everything correctly, here is an example:
`... -audiodev spice,id=sndout1 -device hda-output,audiodev=sndout1 ...`

It was easy to set up, in the guest system you can see that there is an audio device **HD Audio**, but I don't get any sound.

Considered **Vectras** and found this:
`printenv QEMU_AUDIO_DRV
QEMU_AUDIO_DRV=sdl`
I read about it and realized that because of this environment variable in Vectras the sound doesn't work because it constantly uses SDL driver used only for SDL mode.

I found out and tried to do something, but there was just one problem...
`printenv QEMU_AUDIO_DRV`
`QEMU_AUDIO_DRV=sdl`
`export QEMU_AUDIO_DRV=spice`
`printenv QEMU_AUDIO_DRV`
`QEMU_AUDIO_DRV=sdl`
When I try to change this environment variable, it changes it back, thus I cannot change the driver used for the audio output.

**Comment by epicstudios856** [comment]
ok i working on, also we building our spice audio and client

**Comment by Wirdi51** [comment]
Thanks for the information and I hope it works out for you.
